import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import LenisProvider from "./common/lib/lenis/LenisProvider";
import { AnalyticsProvider } from "./common/utils/AnalyticsProvider";
import WAButton from "./common/components/btn/WAButton";
import { CookieBanner } from "./common/components/banner/CookieBanner";
import Nav from "./common/components/nav/Nav";
import { createContract } from "./common/utils/helper-contract";
import { getCompanyData } from "./_domain/services/company.services";
import { getMarketingData } from "./_domain/services/marketing.services";
import { CompanyModel } from "./_domain/model/company.model";
import { MarketingModel } from "./_domain/model/marketing.model";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-primary",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const companyData = await createContract(getCompanyData, CompanyModel);
  const metaData = await createContract(getMarketingData, MarketingModel);

  if (!companyData) return;

  const analyticsConfig = {
    pixelId: metaData?.meta?.pixelId || "",
    testEventCode: metaData?.meta?.testEventCode || "",
    enableCapi: metaData?.meta?.enableCapi || false,

    gtmId: metaData?.google?.gtmId || "",
  };
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {analyticsConfig.gtmId && (
          <noscript>
            <iframe
              src={`https://www.googletagmanager.com/ns.html?id=${analyticsConfig.gtmId}`}
              height="0"
              width="0"
              style={{ display: "none", visibility: "hidden" }}
            />
          </noscript>
        )}

        <LenisProvider>
          <AnalyticsProvider config={analyticsConfig}>
            <Nav companyData={companyData?.serialize()} />
            {children}
            <WAButton data={companyData.serialize()} />
            <CookieBanner />
          </AnalyticsProvider>
        </LenisProvider>
      </body>
    </html>
  );
}
